apiVersion: v1
kind: Service
metadata:
  name: triviawebapp
  labels:
    app: triviawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: triviawebapp